// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { reportOpsEvent } from "@/lib/ops";

// Fase 8: fetch instrumentado — qualquer RPC que falhe no transporte (rede)
// ou com 5xx vira evento rpc_failure, sem tocar nos call sites. 4xx são
// regras de jogo/auth (esperados) e ficam de fora para não poluir o sinal.
function opsFetch(
  input: RequestInfo | URL,
  init?: RequestInit,
): Promise<Response> {
  const url = String(input instanceof Request ? input.url : input);
  const isRpc = url.includes("/rest/v1/rpc/");
  const fn = isRpc ? url.split("/rest/v1/rpc/")[1]?.split("?")[0] : "";
  const report = (status: number | string) => {
    // log_ops_event nunca se auto-reporta (loop infinito se o banco cair)
    if (!isRpc || fn === "log_ops_event") return;
    reportOpsEvent("rpc_failure", { fn, status });
  };
  return fetch(input, init).then(
    (res) => {
      if (res.status >= 500) report(res.status);
      return res;
    },
    (err) => {
      report("network");
      throw err;
    },
  );
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no .env.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: { fetch: opsFetch },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
